import type { Metadata } from "next";
import { Sarabun } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import Providers from "@/components/providers";
import { Sidebar } from "lucide-react";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/common/app-sidbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  suppressHydrationWarning >
   <body className="dark:bg-blue-1">
    

    {/* <SidebarProvider> */}
      {/* <AppSidebar /> */}
        <Providers>   
         {/* <SidebarTrigger /> */}
          {children}
          </Providers>
          {/* </SidebarProvider> */}
        <Toaster />
      </body>
    </html>
  );
}
